{
    xdg.configFile."ghostty/config".text = ''
        background = #333333
        foreground = #C2C2C2
        palette = 0=#333333
        palette = 1=#CCCCCC
        palette = 2=#686868
        palette = 3=#7C7C7C
        palette = 4=#868686
        palette = 5=#5E5E5E
        palette = 6=#B8B8B8
        palette = 7=#A4A4A4
        palette = 8=#A4A4A4
        palette = 9=#CCCCCC
        palette = 10=#686868
        palette = 11=#7C7C7C
        palette = 12=#868686
        palette = 13=#5E5E5E
        palette = 14=#B8B8B8
        palette = 15=#868686
        font-family = BerkeleyMono Nerd Font
        font-feature = +liga
        font-size = 15
        macos-titlebar-style = hidden
        window-decoration = true
        window-theme = auto
        window-padding-color = background
        window-padding-balance = false
        window-padding-y = 0
        window-padding-x = 0
        confirm-close-surface = false
        quit-after-last-window-closed = true
        macos-window-shadow = false
        window-save-state = always
        quick-terminal-animation-duration = 0
        macos-non-native-fullscreen = false
        macos-option-as-alt = true
        adjust-cell-height = 65%
        adjust-cursor-height = 65%
        adjust-underline-position = 15%
        adjust-font-baseline = 10%
        cursor-style = bar
        adjust-cursor-thickness = 2
        cursor-style-blink = true
        mouse-hide-while-typing = true
        clipboard-read = allow
        clipboard-write = allow
        clipboard-trim-trailing-spaces = true
        copy-on-select = clipboard
        keybind = alt+3=text:#
        shell-integration-features = sudo,no-title
    '';
}
