# ./.tmuxinator.yml

name: r18
root: ~/smrtzr/r18/

windows:
  - services:
      layout: main-vertical
      panes:
        - cd ~/smrtzr/r18; nix develop
        - cd ~/smrtzr/java/editor; nix develop
        - cd ~/smrtzr/smrtzr/emulators/local/datastore; nix develop
