local cmd = vim.cmd
Util.map.nl('X', function() cmd('!chmod +x %') end, 'Make file executable')
Util.map.n('<C-d>', '<C-d>zz', 'Down half-page and center')
Util.map.n('<C-u>', '<C-u>zz', 'Up half-page and center')
Util.map.n('<esc>', cmd.noh, 'Escape and clear hlsearch')
Util.map.x('/', '<Esc>/\\%V')
Util.map.n('n', "'Nn'[v:searchforward].'zv'", 'Next Search Result', { expr = true })
Util.map.n('N', "'nN'[v:searchforward].'zv'", 'Prev Search Result', { expr = true })
Util.map.i(',', ',<c-g>u', 'Comma add undo break-point')
Util.map.i('.', '.<c-g>u', 'Period add undo break-point')
Util.map.i(';', ';<c-g>u', 'Semi-colon add undo break-point')
Util.map.v('<', '<gv', 'Dedent reselect')
Util.map.v('>', '>gv', 'Indent reselect')
Util.map.nl('fn', cmd.enew, 'New File')
Util.map.nl('wd', '<C-W>c', 'Delete Window', { remap = true })
Util.map.nl('w', '<c-w>', 'Windows', { remap = true })
Util.map.nl('q', function()
    local cur_tabnr = vim.fn.tabpagenr()
    for _, wininfo in ipairs(vim.fn.getwininfo()) do
        if wininfo.quickfix == 1 and wininfo.tabnr == cur_tabnr then return vim.cmd('cclose') end
    end
    vim.cmd('copen')
end, 'Quickfix List')
Util.map.nl('<tab>]', cmd.tabnext, 'Next')
Util.map.nl('<tab>[', cmd.tabprevious, 'Previous')
Util.map.nl('<tab>d', cmd.tabclose, 'Close current')
Util.map.nl('<tab>o', cmd.tabonly, 'Close other')
Util.map.nl('ba', function() cmd.b('#') end, 'Alternate')
Util.map.n('j', 'gj', 'Navigate through wrapped lines')
Util.map.n('k', 'gk', 'Navigate through wrapped lines')
