Util.req('config.mini.notify')
Util.req('config.mini.icons')
Util.req('config.mini.extra')
Util.req('config.mini.clue')
Util.req('config.mini.statusline')
Util.req('config.mini.completion')
Util.req('config.mini.diff')
Util.req('config.mini.bufremove')
Util.req('config.mini.ai')
-- Util.req('config.mini.files')
Util.req('config.mini.hipatterns')
Util.req('config.mini.jump')
Util.req('config.mini.pairs')
Util.req('config.mini.pick')
Util.req('config.mini.snippets')
Util.req('config.mini.visits')
