return {
    -- "nvim-telescope/telescope.nvim",
    -- branch = "0.1.x",
    -- dependencies = {
    --     "nvim-lua/plenary.nvim",
    --     "nvim-telescope/telescope-ui-select.nvim",
    --     { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
    --     { "nvim-telescope/telescope-live-grep-args.nvim", version = "^1.0.0" },
    -- },
    -- config = function()
    --     local telescope = require("telescope")
    --     local actions = require("telescope.actions")
    --     pcall(require("telescope").load_extension, "fzf")
    --     pcall(require("telescope").load_extension, "harpoon")
    --     pcall(require("telescope").load_extension, "ui-select")
    --     pcall(require("telescope").load_extension, "live_grep_args")
    --
    --     telescope.setup({
    --         defaults = {
    --             path_display = { "smart" },
    --             file_ignore_patterns = {
    --                 "node_modules",
    --             },
    --             mappings = {
    --                 i = {
    --                     ["<C-u>"] = false,
    --                     ["<C-d>"] = false,
    --                     ["<C-n>"] = actions.cycle_history_next,
    --                     ["<C-p>"] = actions.cycle_history_prev,
    --                     ["<C-q>"] = actions.smart_add_to_qflist + actions.open_qflist,
    --                 },
    --                 n = {
    --                     ["d"] = "delete_buffer",
    --                 },
    --             },
    --         },
    --         extensions = {
    --             ["ui-select"] = {
    --                 require("telescope.themes").get_dropdown({
    --                     -- even more opts
    --                 }),
    --             },
    --         },
    --     })
    --
    --     telescope.load_extension("fzf")
    --
    --     -- set keymaps
    --     local keymap = vim.keymap -- for conciseness
    --
    --     keymap.set("n", "<leader>?", require("telescope.builtin").oldfiles, { desc = "[?] Find recently opened files" })
    --     keymap.set("n", "<leader>/", function()
    --         -- You can pass additional configuration to telescope to change theme, layout, etc.
    --         require("telescope.builtin").current_buffer_fuzzy_find(require("telescope.themes").get_dropdown({
    --             winblend = 10,
    --             previewer = false,
    --         }))
    --     end, { desc = "[/] Fuzzily search in current buffer" })
    --
    --     keymap.set("n", "<leader>gb", require("telescope.builtin").git_branches, { desc = "Search [G]it [B]ranches" })
    --     keymap.set("n", "<leader>sf", require("telescope.builtin").find_files, { desc = "[S]earch [F]iles" })
    --     keymap.set("n", "<leader>sb", require("telescope.builtin").buffers, { desc = "[S]earch [B]uffers" })
    --     keymap.set("n", "<leader>sh", require("telescope.builtin").help_tags, { desc = "[S]earch [H]elp" })
    --     keymap.set("n", "<leader>sw", require("telescope.builtin").grep_string, { desc = "[S]earch current [W]ord" })
    --     keymap.set(
    --         "n",
    --         "<leader>sg",
    --         ":lua require('telescope').extensions.live_grep_args.live_grep_args()<CR>",
    --         { desc = "[S]earch by [G]rep", silent = true }
    --     )
    --     keymap.set("n", "<leader>sd", require("telescope.builtin").diagnostics, { desc = "[S]earch [D]iagnostics" })
    -- end,
}
