local o = vim.o

vim.schedule(function() o.clipboard = 'unnamedplus' end)
o.autoread = true
o.mouse = 'a'
o.swapfile = false
o.switchbuf = 'usetab'
o.backup = false
o.writebackup = false
o.undofile = true
o.updatetime = 200
o.breakindent = true
o.cmdheight = 0
o.conceallevel = 2
o.cursorline = true
o.cursorlineopt = 'screenline,number'
o.hlsearch = true
o.laststatus = 2
o.number = true
o.relativenumber = true
o.ruler = false
o.scrolloff = 4
o.sidescrolloff = 8
o.shortmess = 'aoOWFcSCs'
o.showmatch = true
o.showmode = false
o.signcolumn = 'yes'
o.splitbelow = true
o.splitright = true
o.winborder = 'single'
o.wrap = false
o.listchars = table.concat({ 'extends:…', 'nbsp:␣', 'precedes:…', 'tab:» ', 'trail:·' }, ',')
o.breakindentopt = 'list:-1'
o.autoindent = true
o.confirm = true
o.expandtab = true
o.formatoptions = 'rqnl1j'
o.ignorecase = true
o.inccommand = 'split'
o.incsearch = true
o.infercase = true
o.shiftwidth = 0
o.smartcase = true
o.smartindent = true
o.tabstop = 4
o.virtualedit = 'block'
o.foldenable = true
o.foldlevelstart = 99
o.foldmethod = 'expr'
o.foldcolumn = '1'
o.foldtext = ''
o.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
vim.opt.fillchars:append({
    fold = ' ',
    foldopen = '',
    foldclose = '',
    foldsep = ' ',
    foldinner = ' ',
    diff = ' ',
    eob = ' ',
})

vim.opt.complete:remove('t')
o.verbose = 0
o.completeopt = 'menuone,noinsert,popup,preview'
o.spelloptions = 'camel'

o.wildmenu = true
o.wildmode = 'noselect:longest:lastused,full'
